### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by n-semenova** [rofleksey/vk-spa#1]
Добрый день, Алексей!

Интересное, креативное вступление, но, к сожалению, получить список у меня не получилось. Попробовала различные запросы: и по имени, и по id

![image](https://user-images.githubusercontent.com/116729282/198049524-ad183127-700e-4f99-a683-763fbbd70627.png)
![image](https://user-images.githubusercontent.com/116729282/198049632-fd486883-e547-4853-a4c4-dace2732be01.png)

**Comment by rofleksey** [comment]
Здравствуйте! Пожалуйста, нажмите кнопку "Добавить пользователей"! Извините, если не очень понятный интерфейс.

**Comment by rofleksey** [comment]
Ввод в поле "Список пользователей" ищет среди уже добавленных =)

**Comment by n-semenova** [comment]
Алексей, добрый день! Все получилось ))
